In [1]:
import pandas as pd
import os

In [4]:
# Diretório dos arquivos Excel
diretorio = r"C:\VilarLearn\Source\Travel"

# Lista para armazenar os DataFrames dos arquivos
dados = []

# Iterar sobre os arquivos Excel no diretório
for arquivo in os.listdir(diretorio):
    if arquivo.endswith('.xlsx'):
        caminho_arquivo = os.path.join(diretorio, arquivo)
        dados.append(pd.read_excel(caminho_arquivo))

# Consolidar os dados em um único DataFrame
consolidado = pd.concat(dados, ignore_index=True)

# Exibir o DataFrame consolidado
consolidado

,Número de Voo,Companhia Aérea,Origem,Destino,Data Partida,Data Chegada,Preço,Número de Passageiros,Classe
0,1165,Black-Castro,Lake Ashleyfurt,Rodriguezton,2024-11-03,2024-08-26,556.22,2,Executiva
1,8714,"Vega, Robinson and Richard",Ianland,Port Cathyville,2024-06-04,2024-11-07,550.95,1,Executiva
2,1042,"Anderson, Gonzalez and Kaiser",East Lindsayville,Davidview,2024-12-17,2024-10-04,607.00,3,Executiva
3,9423,Wilkins Inc,North Donald,Port Douglas,2024-09-16,2024-09-06,580.23,2,Executiva
4,9986,Gray-Vargas,Princemouth,Sotobury,2024-04-19,2024-12-23,900.34,1,Primeira Classe
5,4720,"Mccann, Long and Moreno",Port David,Annview,2024-01-03,2024-06-08,602.35,3,Econômica
6,5665,Jones Inc,West Catherine,Robertbury,2024-08-25,2024-05-08,705.07,4,Primeira Classe
7,2584,Reynolds Ltd,New Richard,Janetshire,2024-03-27,2024-10-04,689.14,3,Primeira Classe
8,2157,Cohen-Olson,Davischester,Port Zacharyside,2024-12-15,2024-04-04,951.13,5,Econômica
9,6684,Ayers PLC,Donnabury,Amychester,2024-11-01,2024-12-21,131.55,3,Executiva
10,3382,Harrington LLC,Lake Brittany,East Sheilamouth,2024-01-04,2024-04-29,796.80,5,Econômica
11,1089,Becker-House,Chapmanfort,Mooreton,2024-03-29,2024-08-18,556.49,2,Econômica
12,7054,Miller-Yu,Robertoberg,Lake Travis,2024-02-03,2024-07-28,267.06,1,Executiva
13,9385,Fernandez-Harris,Lake Eric,Brianchester,2024-08-28,2024-03-31,807.12,3,Executiva
14,4976,"Russell, Bryant and Rivera",Ryanburgh,North Gary,2024-07-29,2024-05-07,444.55,1,Executiva
15,1165,Black-Castro,Lake Ashleyfurt,Rodriguezton,2024-11-03,2024-08-26,556.22,2,Executiva
16,8714,"Vega, Robinson and Richard",Ianland,Port Cathyville,2024-06-04,2024-11-07,550.95,1,Executiva
17,1042,"Anderson, Gonzalez and Kaiser",East Lindsayville,Davidview,2024-12-17,2024-10-04,607.00,3,Executiva
18,9423,Wilkins Inc,North Donald,Port Douglas,2024-09-16,2024-09-06,580.23,2,Executiva
19,9986,Gray-Vargas,Princemouth,Sotobury,2024-04-19,2024-12-23,900.34,1,Primeira Classe
20,4720,"Mccann, Long and Moreno",Port David,Annview,2024-01-03,2024-06-08,602.35,3,Econômica
21,5665,Jones Inc,West Catherine,Robertbury,2024-08-25,2024-05-08,705.07,4,Primeira Classe
22,2584,Reynolds Ltd,New Richard,Janetshire,2024-03-27,2024-10-04,689.14,3,Primeira Classe
23,2157,Cohen-Olson,Davischester,Port Zacharyside,2024-12-15,2024-04-04,951.13,5,Econômica
24,6684,Ayers PLC,Donnabury,Amychester,2024-11-01,2024-12-21,131.55,3,Executiva
25,3382,Harrington LLC,Lake Brittany,East Sheilamouth,2024-01-04,2024-04-29,796.80,5,Econômica
26,1089,Becker-House,Chapmanfort,Mooreton,2024-03-29,2024-08-18,556.49,2,Econômica
27,7054,Miller-Yu,Robertoberg,Lake Travis,2024-02-03,2024-07-28,267.06,1,Executiva
28,9385,Fernandez-Harris,Lake Eric,Brianchester,2024-08-28,2024-03-31,807.12,3,Executiva
29,4976,"Russell, Bryant and Rivera",Ryanburgh,North Gary,2024-07-29,2024-05-07,444.55,1,Executiva

In [5]:
from sqlalchemy import create_engine

# Configurações da conexão com o Azure SQL
server = 'seu_server.database.windows.net'
database = 'seu_banco_de_dados'
username = 'Seu_usuario'
password = 'Sua_senha'
driver = 'ODBC Driver 17 for SQL Server'

# Construir a string de conexão
conn_str = f"mssql+pyodbc://{username}:{password}@{server}/{database}?driver={driver}"

# Criar uma conexão com o banco de dados
engine = create_engine(conn_str)

# Nome da tabela no Azure SQL
nome_tabela = 'Viagens'

# Enviar DataFrame para o Azure SQL
consolidado.to_sql(nome_tabela, con=engine, if_exists='replace', index=False)

# Fechar a conexão
engine.dispose()